### ISSUE TITLE
nrf_cli syntax error whenever a nRF52840 Dongle is connected

### ISSUE THREAD

**Issue by czeslawmakarski** [wbober/nrf5-scripts#1]
Whenever the nRF52840 Dongle is connected, there seems to be some bash syntax error:
```
czma@ns-czma: ~/Downloads $ nrf_cli
bash: [: C5571D8CC6F1: integer expression expected
```

**Comment by wbober** [comment]
Hi, Thanks for opening a ticket. As this is an open source project you're more than welcome to submit a PR!
